// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_attendance from "./routes/api/attendance.ts";
import * as $api_delete_all from "./routes/api/delete_all.ts";
import * as $api_delete_one from "./routes/api/delete_one.ts";
import * as $date_dateStr_ from "./routes/date/[dateStr].tsx";
import * as $index from "./routes/index.tsx";
import * as $Calendar from "./islands/Calendar.tsx";
import * as $DateForm from "./islands/DateForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/attendance.ts": $api_attendance,
    "./routes/api/delete_all.ts": $api_delete_all,
    "./routes/api/delete_one.ts": $api_delete_one,
    "./routes/date/[dateStr].tsx": $date_dateStr_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Calendar.tsx": $Calendar,
    "./islands/DateForm.tsx": $DateForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
